#!/usr/bin/env python3
"""Regenerate the recall/MRR-vs-corpus-size SVG in reports/experiments.html from evals/results/history.jsonl."""
import json, re, pathlib
root = pathlib.Path(__file__).resolve().parent.parent
hist = [json.loads(l) for l in (root/'evals/results/history.jsonl').read_text().splitlines() if l.strip()]
PMIN, PMAX = 40, 400
def X(p): return round(60 + (p-PMIN)*560/(PMAX-PMIN), 1)
def Y(v): return round(220 - (v-0.80)*1000)
lex = [h for h in hist if h.get('mode') == 'lexical']
hyb = [h for h in hist if h.get('mode') == 'hybrid']
pts = lambda rows, m: ' '.join(f"{X(h['n_pages'])},{Y(h['metrics'][m])}" for h in rows)
circ = lambda rows, m, r: ''.join(f'<circle cx="{X(h["n_pages"])}" cy="{Y(h["metrics"][m])}" r="{r}"/>' for h in rows)
ticks = ''.join(f'<text x="{X(p)}" y="240" text-anchor="middle">{p}</text>' for p in range(PMIN, PMAX+1, 60))
svg = f'''<svg viewBox="0 0 640 260" width="100%" role="img" aria-label="recall@1 and MRR versus wiki page count">
  <line class="axis" x1="60" y1="20" x2="60" y2="220"/><line class="axis" x1="60" y1="220" x2="620" y2="220"/>
  <line class="grid" x1="60" y1="20" x2="620" y2="20"/><line class="grid" x1="60" y1="70" x2="620" y2="70"/><line class="grid" x1="60" y1="120" x2="620" y2="120"/><line class="grid" x1="60" y1="170" x2="620" y2="170"/>
  <text x="52" y="24" text-anchor="end">1.00</text><text x="52" y="74" text-anchor="end">0.95</text><text x="52" y="124" text-anchor="end">0.90</text><text x="52" y="174" text-anchor="end">0.85</text>
  {ticks}
  <text x="340" y="256" text-anchor="middle">pages indexed (wiki markdown files incl. generated index/log)</text>
  <!-- generated by reports/chart.py from evals/results/history.jsonl: x = 60 + (pages-{PMIN})*560/{PMAX-PMIN} ; y = 220 - (v-0.80)*1000 -->
  <polyline class="l2" points="{pts(lex,'recall@1')}"/>
  <polyline class="l1" points="{pts(lex,'mrr')}"/>
  <g class="pt2">{circ(lex,'recall@1',3.5)}</g>
  <g class="pt">{circ(lex,'mrr',3.5)}</g>
  <g class="hy">{circ(hyb,'recall@1',4)}{circ(hyb,'mrr',4)}</g>
  <text x="606" y="{Y(lex[-1]['metrics']['mrr'])-6}" class="lbl">MRR (lexical)</text>
  <text x="606" y="{Y(lex[-1]['metrics']['recall@1'])+14}">recall@1 (lexical)</text>
  <text x="120" y="56" style="fill:var(--warn)">hybrid</text>
</svg>'''
p = root/'reports/experiments.html'
html = p.read_text()
new, n = re.subn(r'<svg viewBox="0 0 640 260".*?</svg>', lambda m: svg, html, count=1, flags=re.S)
assert n == 1
p.write_text(new)
print(f"chart: {len(lex)} lexical, {len(hyb)} hybrid points; last lexical {lex[-1]['n_pages']} pages mrr {lex[-1]['metrics']['mrr']:.3f}")
