#!/usr/bin/env python3
"""Regenerate wiki/index.md and wiki/log.md from page frontmatter and wiki/log/*.md.

Exits non-zero on: missing/invalid frontmatter, duplicate slugs; with --strict also on links to missing pages.
Usage: scripts/build_index.py [--check]   (--check: validate only, do not write)
"""
import re, sys, pathlib, collections

ROOT = pathlib.Path(__file__).resolve().parent.parent
WIKI = ROOT / "wiki"
DIRS = ["concepts", "sources", "syntheses", "paths"]
REQUIRED = ["title", "type", "section", "tags", "summary"]

def parse_frontmatter(text: str):
    m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    if not m:
        return None
    fm = {}
    for line in m.group(1).splitlines():
        if ":" in line and not line.startswith((" ", "-")):
            k, v = line.split(":", 1)
            v = v.strip()
            if v.startswith("[") and v.endswith("]"):
                v = [x.strip().strip("'\"") for x in v[1:-1].split(",") if x.strip()]
            else:
                v = v.strip("'\"")
            fm[k.strip()] = v
    return fm

def main():
    check = "--check" in sys.argv
    pages = {}
    errors = []
    for d in DIRS:
        for p in sorted((WIKI / d).glob("*.md")):
            slug = p.stem
            text = p.read_text()
            fm = parse_frontmatter(text)
            if fm is None:
                errors.append(f"{p}: missing frontmatter"); continue
            missing = [k for k in REQUIRED if k not in fm]
            if missing:
                errors.append(f"{p}: missing frontmatter keys {missing}")
            if slug in pages:
                errors.append(f"duplicate slug {slug}: {p} and {pages[slug]['path']}")
            pages[slug] = {"path": p, "dir": d, "fm": fm, "text": text}
    # link check + inbound counts
    inbound = collections.Counter()
    wanted = collections.Counter()  # links to pages that do not exist yet
    for slug, pg in pages.items():
        for link in re.findall(r"\[\[([^\]|#]+)(?:[|#][^\]]*)?\]\]", pg["text"]):
            link = link.strip()
            if link not in pages:
                wanted[link] += 1
            elif link != slug:
                inbound[link] += 1
        for src in (pg["fm"].get("sources") or []):
            if isinstance(src, str) and src in pages and src != slug:
                inbound[src] += 1
    strict = "--strict" in sys.argv
    if strict and wanted:
        errors += [f"wanted page [[{w}]] ({n} links)" for w, n in wanted.most_common()]
    if errors:
        print("\n".join(errors)); sys.exit(1)
    if check:
        print(f"ok: {len(pages)} pages, {len(wanted)} wanted"); return
    # index.md
    out = ["# Index", "", f"{len(pages)} pages. Generated by scripts/build_index.py — do not edit.", ""]
    for d, title in zip(DIRS, ["Concepts", "Sources", "Syntheses", "Learning paths"]):
        items = sorted((s, pg) for s, pg in pages.items() if pg["dir"] == d)
        if not items:
            continue
        out.append(f"## {title} ({len(items)})"); out.append("")
        by_section = collections.defaultdict(list)
        for s, pg in items:
            by_section[str(pg["fm"].get("section", "?"))].append((s, pg))
        for sec in sorted(by_section, key=lambda x: [int(t) if t.isdigit() else 0 for t in x.split(".")]):
            out.append(f"### §{sec}")
            for s, pg in by_section[sec]:
                fm = pg["fm"]
                out.append(f"- [[{s}]] — **{fm.get('title', s)}**: {fm.get('summary', '')} (in: {inbound[s]})")
            out.append("")
    if wanted:
        out.append("## Wanted pages (linked but not yet written)"); out.append("")
        for w, n in wanted.most_common():
            out.append(f"- {w} ({n} links)")
        out.append("")
    (WIKI / "index.md").write_text("\n".join(out) + "\n")
    # log.md
    entries = sorted((WIKI / "log").glob("*.md"), reverse=True)
    log = ["# Log", "", "Newest first. Generated from wiki/log/*.md — do not edit.", ""]
    for e in entries:
        log.append(e.read_text().strip()); log.append("")
    (WIKI / "log.md").write_text("\n".join(log) + "\n")
    orphans = [s for s in pages if inbound[s] == 0]
    print(f"ok: {len(pages)} pages, {len(entries)} log entries, {len(wanted)} wanted, {len(orphans)} orphans" + (": " + ", ".join(orphans[:15]) if orphans else ""))

if __name__ == "__main__":
    main()
